---
version: '3'
services:
  netbox:
    image: betacloud/netbox:v2.3.3
    depends_on:
      - postgres
    environment:
      SUPERUSER_NAME: dragon
      SUPERUSER_EMAIL: operations@betacloud.io
      SUPERUSER_PASSWORD: password
    volumes:
      - ./configuration.py:/configuration.py:ro
      - netbox-nginx-config:/etc/netbox-nginx/
      - netbox-static-files:/opt/netbox/netbox/static
  nginx:
    image: nginx:1.13-alpine
    command: nginx -g 'daemon off;' -c /etc/netbox-nginx/nginx.conf
    depends_on:
      - netbox
    ports:
      - 80
    volumes:
      - netbox-static-files:/opt/netbox/netbox/static
      - netbox-nginx-config:/etc/netbox-nginx/
  postgres:
    image: postgres:9.6-alpine
    environment:
      POSTGRES_USER: netbox
      POSTGRES_PASSWORD: password
      POSTGRES_DB: netbox
volumes:
  netbox-static-files:
    driver: local
  netbox-nginx-config:
    driver: local
